apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
  name: tkr-resolver-cluster-webhook-selfsigned-issuer
  namespace: tanzu-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
  name: tkr-resolver-cluster-webhook-serving-cert
  namespace: tanzu-system
spec:
  dnsNames:
  - tkr-resolver-cluster-webhook-service.tanzu-system.svc
  - tkr-resolver-cluster-webhook-service-cert.tanzu-system.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: tkr-resolver-cluster-webhook-selfsigned-issuer
  secretName: tkr-resolver-cluster-webhook-service-cert